package de.demo.weatherapi.enums;

import lombok.Getter;

/**
 * Country Codes ENUM - utility enum to easily lookup / map country codes.
 *
 * @author Dwight Egerton
 * @since 0.0.1
 */
@Getter
@SuppressWarnings("unused")
public enum CountryCodeEnum {
    AC("Ascension Island"),
    AD("Andorra"),
    AE("United Arab Emirates"),
    AF("Afghanistan"),
    AG("Antigua and Barbuda"),
    AI("Anguilla"),
    AL("Albania"),
    AM("Armenia"),
    AN("Netherlands Antilles"),
    AO("Angola"),
    AQ("Antarctica"),
    AR("Argentina"),
    AS("American Samoa"),
    AT("Austria"),
    AU("Australia"),
    AW("Aruba"),
    AX("Åland Islands"),
    AZ("Azerbaijan"),
    BA("Bosnia and Herzegovina"),
    BB("Barbados"),
    BD("Bangladesh"),
    BE("Belgium"),
    BF("Burkina Faso"),
    BG("Bulgaria"),
    BH("Bahrain"),
    BI("Burundi"),
    BJ("Benin"),
    BL("Saint Barthélemy"),
    BM("Bermuda"),
    BN("Brunei Darussalam"),
    BO("Bolivia, Plurinational State of"),
    BQ("Bonaire, Sint Eustatius and Saba"),
    BR("Brazil"),
    BS("Bahamas"),
    BT("Bhutan"),
    BU("Burma"),
    BV("Bouvet Island"),
    BW("Botswana"),
    BY("Belarus"),
    BZ("Belize"),
    CA("Canada"),
    CC("Cocos (Keeling) Islands"),
    CD("Congo, the Democratic Republic of the"),
    CF("Central African Republic"),
    CG("Congo"),
    CH("Switzerland"),
    CI("Côte d'Ivoire"),
    CK("Cook Islands"),
    CL("Chile"),
    CM("Cameroon"),
    CN("China"),
    CO("Colombia"),
    CP("Clipperton Island"),
    CR("Costa Rica"),
    CS("Serbia and Montenegro"),
    CU("Cuba"),
    CV("Cape Verde"),
    CW("Curaçao"),
    CX("Christmas Island"),
    CY("Cyprus"),
    CZ("Czech Republic"),
    DE("Germany"),
    DG("Diego Garcia"),
    DJ("Djibouti"),
    DK("Denmark"),
    DM("Dominica"),
    DO("Dominican Republic"),
    DZ("Algeria"),
    EA("Ceuta, Melilla"),
    EC("Ecuador"),
    EE("Estonia"),
    EG("Egypt"),
    EH("Western Sahara"),
    ER("Eritrea"),
    ES("Spain"),
    ET("Ethiopia"),
    EU("European Union"),
    EZ("Eurozone"),
    FI("Finland"),
    FJ("Fiji"),
    FK("Falkland Islands (Malvinas)"),
    FM("Micronesia, Federated States of"),
    FO("Faroe Islands"),
    FR("France"),
    FX("France, Metropolitan"),
    GA("Gabon"),
    GB("United Kingdom"),
    GD("Grenada"),
    GE("Georgia"),
    GF("French Guiana"),
    GG("Guernsey"),
    GH("Ghana"),
    GI("Gibraltar"),
    GL("Greenland"),
    GM("Gambia"),
    GN("Guinea"),
    GP("Guadeloupe"),
    GQ("Equatorial Guinea"),
    GR("Greece"),
    GS("South Georgia and the South Sandwich Islands"),
    GT("Guatemala"),
    GU("Guam"),
    GW("Guinea-Bissau"),
    GY("Guyana"),
    HK("Hong Kong"),
    HM("Heard Island and McDonald Islands"),
    HN("Honduras"),
    HR("Croatia"),
    HT("Haiti"),
    HU("Hungary"),
    IC("Canary Islands"),
    ID("Indonesia"),
    IE("Ireland"),
    IL("Israel"),
    IM("Isle of Man"),
    IN("India"),
    IO("British Indian Ocean Territory"),
    IQ("Iraq"),
    IR("Iran, Islamic Republic of"),
    IS("Iceland"),
    IT("Italy"),
    JE("Jersey"),
    JM("Jamaica"),
    JO("Jordan"),
    JP("Japan"),
    KE("Kenya"),
    KG("Kyrgyzstan"),
    KH("Cambodia"),
    KI("Kiribati"),
    KM("Comoros"),
    KN("Saint Kitts and Nevis"),
    KP("Korea, Democratic People's Republic of"),
    KR("Korea, Republic of"),
    KW("Kuwait"),
    KY("Cayman Islands"),
    KZ("Kazakhstan"),
    LA("Lao People's Democratic Republic"),
    LB("Lebanon"),
    LC("Saint Lucia"),
    LI("Liechtenstein"),
    LK("Sri Lanka"),
    LR("Liberia"),
    LS("Lesotho"),
    LT("Lithuania"),
    LU("Luxembourg"),
    LV("Latvia"),
    LY("Libya"),
    MA("Morocco"),
    MC("Monaco"),
    MD("Moldova, Republic of"),
    ME("Montenegro"),
    MF("Saint Martin (French part)"),
    MG("Madagascar"),
    MH("Marshall Islands"),
    MK("North Macedonia, Republic of"),
    ML("Mali"),
    MM("Myanmar"),
    MN("Mongolia"),
    MO("Macao"),
    MP("Northern Mariana Islands"),
    MQ("Martinique"),
    MR("Mauritania"),
    MS("Montserrat"),
    MT("Malta"),
    MU("Mauritius"),
    MV("Maldives"),
    MW("Malawi"),
    MX("Mexico"),
    MY("Malaysia"),
    MZ("Mozambique"),
    NA("Namibia"),
    NC("New Caledonia"),
    NE("Niger"),
    NF("Norfolk Island"),
    NG("Nigeria"),
    NI("Nicaragua"),
    NL("Netherlands"),
    NO("Norway"),
    NP("Nepal"),
    NR("Nauru"),
    NT("Neutral Zone"),
    NU("Niue"),
    NZ("New Zealand"),
    OM("Oman"),
    PA("Panama"),
    PE("Peru"),
    PF("French Polynesia"),
    PG("Papua New Guinea"),
    PH("Philippines"),
    PK("Pakistan"),
    PL("Poland"),
    PM("Saint Pierre and Miquelon"),
    PN("Pitcairn"),
    PR("Puerto Rico"),
    PS("Palestine, State of"),
    PT("Portugal"),
    PW("Palau"),
    PY("Paraguay"),
    QA("Qatar"),
    RE("Réunion"),
    RO("Romania"),
    RS("Serbia"),
    RU("Russian Federation"),
    RW("Rwanda"),
    SA("Saudi Arabia"),
    SB("Solomon Islands"),
    SC("Seychelles"),
    SD("Sudan"),
    SE("Sweden"),
    SF("Finland"),
    SG("Singapore"),
    SH("Saint Helena, Ascension and Tristan da Cunha"),
    SI("Slovenia"),
    SJ("Svalbard and Jan Mayen"),
    SK("Slovakia"),
    SL("Sierra Leone"),
    SM("San Marino"),
    SN("Senegal"),
    SO("Somalia"),
    SR("Suriname"),
    SS("South Sudan"),
    ST("Sao Tome and Principe"),
    SU("USSR"),
    SV("El Salvador"),
    SX("Sint Maarten (Dutch part)"),
    SY("Syrian Arab Republic"),
    SZ("Eswatini"),
    TA("Tristan da Cunha"),
    TC("Turks and Caicos Islands"),
    TD("Chad"),
    TF("French Southern Territories"),
    TG("Togo"),
    TH("Thailand"),
    TJ("Tajikistan"),
    TK("Tokelau"),
    TL("Timor-Leste"),
    TM("Turkmenistan"),
    TN("Tunisia"),
    TO("Tonga"),
    TP("East Timor"),
    TR("Turkey"),
    TT("Trinidad and Tobago"),
    TV("Tuvalu"),
    TW("Taiwan, Province of China"),
    TZ("Tanzania, United Republic of"),
    UA("Ukraine"),
    UG("Uganda"),
    UK("United Kingdom"),
    UM("United States Minor Outlying Islands"),
    US("United States"),
    UY("Uruguay"),
    UZ("Uzbekistan"),
    VA("Holy See (Vatican City State)"),
    VC("Saint Vincent and the Grenadines"),
    VE("Venezuela, Bolivarian Republic of"),
    VG("Virgin Islands, British"),
    VI("Virgin Islands, U.S."),
    VN("Viet Nam"),
    VU("Vanuatu"),
    WF("Wallis and Futuna"),
    WS("Samoa"),
    XI("Northern Ireland"),
    XU("United Kingdom (excluding Northern Ireland)"),
    XK("Kosovo, Republic of"),
    YE("Yemen"),
    YT("Mayotte"),
    YU("Yugoslavia"),
    ZA("South Africa"),
    ZM("Zambia"),
    ZR("Zaire"),
    ZW("Zimbabwe");

    private final String country;

    CountryCodeEnum(String country) {
        this.country = country;
    }

    public static CountryCodeEnum fromString(String value) {
        if (value != null) {
            for (CountryCodeEnum c : values()) {
                if (value.equalsIgnoreCase(c.name())) return c;
                else if (value.equalsIgnoreCase(c.getCountry())) return c;
            }
        }
        return null;
    }
}
